apps/boards/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import *

app_name="boards"

urlpatterns = [
    path('coverage/', login_required(views.CoverageView.as_view()), name='index_cov'),
    path('coverage/list/', views.ListCoverage.as_view(), name='list_rn'),
    path('coverage/printNominal/', views.PrintNominal.as_view(), name='print_nom'),
]

apps/dashboard/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import *

app_name="dashboard"

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', login_required(views.logoutUser), name='logout'),
    path('home/', login_required(views.HomeView.as_view()), name='home'),
    path('dashboard/', login_required(views.DahboardView.as_view()), name='dash'),
    path('dashboard/api/', views.AttentionToday.as_view(), name='attentions'),
    path('dashboard/print/', views.PrintAttentionToday.as_view(), name='print_attentions'),
]

apps/follow_up/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import permission_required, login_required

app_name='follow_up'

urlpatterns = [
    path('', login_required(KidsView.as_view()), name='index_boy'),
    path('search/', SearchKidsView.as_view(), name='search_boy'),
    path('anemiaKids/', login_required(AnemiaKidsView.as_view()), name='index_anemia'),
    path('anemiaKids/search/', NominalAnemia.as_view(), name='anemia_search'),
    path('anemiaKids/printNominal/', PrintNomAnem.as_view(), name='anemia_print'),
    path('goals/', login_required(MetasPriorView.as_view()), name='index_goals'),
    path('goals/list/', ListMetasPrior.as_view(), name='goals_list'),
    path('goals/avance/', AdvMetasPriorXAct.as_view(), name='goals_avance'),
    path('goals/printExcel/', PrintGoals.as_view(), name='goals_print'),
    path('inmunization/', login_required(InmunizationView.as_view()), name='index_inmunization'),
    path('inmunization/list/', NominalInmunization.as_view(), name='list_inmunization'),
    path('inmunization/listCant/', ConteoInmunization.as_view(), name='list_inmunization'),
    path('inmunization/print/', PrintInmunization.as_view(), name='print_inmunization'),
]

essalud/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    path('follow_up/',include('apps.follow_up.urls', namespace='follow_up')),
    path('packages/',include('apps.packages.urls', namespace='packages')),
    path('boards/',include('apps.boards.urls', namespace='boards')),
    path('person/',include('apps.person.urls', namespace='person')),
]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
User = get_user_model()

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args,**kwargs)
        self.fields['username'].widget.attrs['class']='form-control has-feedback-left'
        self.fields['username'].widget.attrs['placeholder']='Usuario'
        self.fields['password'].widget.attrs['class']='form-control has-feedback-left'
        self.fields['password'].widget.attrs['placeholder']='Contraseña'

    def clean(self):
        user_found = User.objects.filter(username = self.cleaned_data['username']).exists()
        if not user_found:
            self.add_error('username', 'Usuario no Encontrado.')
        else:
            user = User.objects.get(username = self.cleaned_data['username'])
            if  not user.check_password(self.cleaned_data['password']):
                self.add_error('password', 'Contraseña Incorrecta.')


class ChangePassForm(forms.Form):
    new_pass = forms.CharField(max_length=100, widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Nueva contraseña',
            'v-model':'form.new_pass',
        }
    ))
    new_pass_r = forms.CharField(max_length=100, widget=forms.PasswordInput(
        attrs={
            'class': 'form-control m-b-10 m-t-10',
            'placeholder': 'Repita contraseña',
            'v-model': 'form.new_pass_r',
        }
    ))

apps/dashboard/views.py
from django.http import JsonResponse, HttpResponse, QueryDict
from django.core import serializers

from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, FormView, View

from django.contrib.auth import authenticate, login, logout, get_user_model
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.http import HttpResponseRedirect

from datetime import date, datetime
from django.db import connection
import json
import locale

# library excel
from openpyxl import Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side, Color
from apps.main.models import Departamento, Provincia, Distrito, Establecimiento

User = get_user_model()
from apps.person.models import Person
from .forms import LoginForm


# Create your views here.
class HomeView(TemplateView):
    template_name = 'base.html'


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('dashboard:dash')

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)

    #verifica la petición
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)

        try:
            ObjPerson = Person.objects.get(pk=user.id_person.id)
            ObjUser = User.objects.get(pk=user.pk)
            if ObjUser.type_ca == 'CA':
                name_ca = Establecimiento.objects.get(codigo=ObjUser.code_ca)
            elif ObjUser.type_ca == 'DS':
                name_ca = Distrito.objects.get(codigo=ObjUser.code_ca)
            elif ObjUser.type_ca == 'PR':
                name_ca = Provincia.objects.get(codigo=ObjUser.code_ca)
            elif ObjUser.type_ca == 'DP':
                name_ca = Departamento.objects.get(codigo=ObjUser.code_ca)

            self.request.session['sytem'] = { 'full_name': ObjPerson.last_name0+' '+ObjPerson.last_name1+', '+ObjPerson.names.title(),
                                            'doc': ObjPerson.pdoc,
                                            'typeca': ObjUser.type_ca, 'codeca': ObjUser.code_ca, 'nombreca': name_ca.nombre }

        except:
            print("Hay un error en los valores de entrada")

        return super(LoginView, self).form_valid(form)


def logoutUser(request):
    logout(request)
    return HttpResponseRedirect('/')


class DahboardView(TemplateView):
    template_name = 'dash.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session['sytem']['typeca'] == 'CA':
            context['establecimiento'] = Establecimiento.objects.filter(codigo=self.request.session['sytem']['codeca'])
        elif self.request.session['sytem']['typeca'] == 'DS':
            context['establecimiento'] = Establecimiento.objects.filter(dist_id=self.request.session['sytem']['codeca'])
        elif self.request.session['sytem']['typeca'] == 'PR':
            context['establecimiento'] = Establecimiento.objects.filter(prov_id=self.request.session['sytem']['codeca'])
        elif self.request.session['sytem']['typeca'] == 'DP':
            context['establecimiento'] = Establecimiento.objects.filter(dep_id=self.request.session['sytem']['codeca'])
        return context


class AttentionToday(View):
    def get(self, request, *args, **kwargs):
        mes = request.GET['mes']
        if len(request.GET['mes']) == 1:
            mes = '0'+request.GET['mes']
        else:
            mes = request.GET['mes']

        a = connection.cursor()
        a.execute("""SELECT cod_dep, cod_prov, cod_dist, cod_eess, establecimiento, ape_nombres, fec_nac, documento, Convert(Integer, Datediff(Day, [fec_nac], EOMONTH('%s-%s-01'))/30) Edad,
                    CASE WHEN CRED11 IS NOT NULL THEN CONCAT(CRED11, ' / CRED11')
                        WHEN CRED10 IS NOT NULL THEN CONCAT(CRED10, ' / CRED10')
                        WHEN CRED9 IS NOT NULL THEN CONCAT(CRED9, ' / CRED9')
                        WHEN CRED8 IS NOT NULL THEN CONCAT(CRED8, ' / CRED8')
                        WHEN CRED7 IS NOT NULL THEN CONCAT(CRED7, ' / CRED7')
                        WHEN CRED6 IS NOT NULL THEN CONCAT(CRED6, ' / CRED6')
                        WHEN CRED5 IS NOT NULL THEN CONCAT(CRED5, ' / CRED5')
                        WHEN CRED4 IS NOT NULL THEN CONCAT(CRED4, ' / CRED4')
                        WHEN CRED3 IS NOT NULL THEN CONCAT(CRED3, ' / CRED3')
                        WHEN CRED2 IS NOT NULL THEN CONCAT(CRED2, ' / CRED2')
                        WHEN CRED1 IS NOT NULL THEN CONCAT(CRED1, ' / CRED1')
                        WHEN ctrl4rn IS NOT NULL THEN CONCAT(ctrl4rn, ' / CRED4_RN')
                        WHEN ctrl3rn IS NOT NULL THEN CONCAT(ctrl3rn, ' / CRED3_RN')
                        WHEN ctrl2rn IS NOT NULL THEN CONCAT(ctrl2rn, ' / CRED2_RN')
                        WHEN ctrl1rn IS NOT NULL THEN CONCAT(ctrl1rn, ' / CRED1_RN')
                    END ULT_CRED,
                    CASE WHEN suple11 IS NOT NULL THEN CONCAT(suple11, ' / SUPLE11')
                        WHEN suple10 IS NOT NULL THEN CONCAT(suple10, ' / SUPLE10')
                        WHEN suple9 IS NOT NULL THEN CONCAT(suple9, ' / SUPLE9')
                        WHEN suple8 IS NOT NULL THEN CONCAT(suple8, ' / SUPLE8')
                        WHEN suple7 IS NOT NULL THEN CONCAT(suple7, ' / SUPLE7')
                        WHEN suple6 IS NOT NULL THEN CONCAT(suple6, ' / SUPLE6')
                        WHEN suple5 IS NOT NULL THEN CONCAT(suple5, ' / SUPLE5')
                        WHEN suple4 IS NOT NULL THEN CONCAT(suple4, ' / SUPLE4')
                    ELSE null end ULT_SUPLE,
                    neumo2, rota2, polio2, penta2, neumo4, rota4, penta4, polio4, polio6, penta6,
                    CASE WHEN ctrl1rn IS NULL THEN 'CRED1RN' END C1RN,
                        CASE WHEN ctrl2rn IS NULL THEN 'CRED2RN' END C2RN,
                        CASE WHEN ctrl3rn IS NULL THEN 'CRED3RN' END C3RN,
                        CASE WHEN ctrl4rn IS NULL THEN 'CRED4RN' END C4RN,
                        CASE WHEN CRED1 IS NULL THEN 'CRED1' END C1,
                        CASE WHEN CRED2 IS NULL THEN 'CRED2' END C2,
                        CASE WHEN CRED3 IS NULL THEN 'CRED3' END C3,
                        CASE WHEN CRED4 IS NULL THEN 'CRED4' END C4,
                        CASE WHEN CRED5 IS NULL THEN 'CRED5' END C5,
                        CASE WHEN CRED6 IS NULL THEN 'CRED6' END C6,
                        CASE WHEN CRED7 IS NULL THEN 'CRED7' END C7,
                        CASE WHEN CRED8 IS NULL THEN 'CRED8' END C8,
                        CASE WHEN CRED9 IS NULL THEN 'CRED9' END C9,
                        CASE WHEN CRED10 IS NULL THEN 'CRED10' END C10,
                        CASE WHEN CRED11 IS NULL THEN 'CRED11' END C11,
                        CASE WHEN SUPLE4 IS NULL THEN 'SPL4' END SPL4,
                        CASE WHEN SUPLE5 IS NULL THEN 'SPL5' END SPL5,
                        CASE WHEN SUPLE6 IS NULL THEN 'SPL6' END SPL6,
                        CASE WHEN SUPLE7 IS NULL THEN 'SPL7' END SPL7,
                        CASE WHEN SUPLE8 IS NULL THEN 'SPL8' END SPL8,
                        CASE WHEN SUPLE9 IS NULL THEN 'SPL9' END SPL9,
                        CASE WHEN SUPLE10 IS NULL THEN 'SPL10' END SPL10,
                        CASE WHEN SUPLE11 IS NULL THEN 'SPL11' END SPL11,
                        CASE WHEN neumo2 IS NULL THEN 'NEUMO2M' END neu2,
                        CASE WHEN rota2 IS NULL THEN 'ROTA2M' END rot2,
                        CASE WHEN polio2 IS NULL THEN 'POLIO2M' END pol2,
                        CASE WHEN penta2 IS NULL THEN 'PENTA2M' END pen2,
                        CASE WHEN neumo4 IS NULL THEN 'NEUMO4M' END neu4,
                        CASE WHEN rota4 IS NULL THEN 'ROTA4M' END rot4,
                        CASE WHEN penta4 IS NULL THEN 'PENTA4M' END pen4,
                        CASE WHEN polio4 IS NULL THEN 'POLIO4M' END pol4,
                        CASE WHEN polio6 IS NULL THEN 'POLIO6M' END pol6,
                        CASE WHEN penta6 IS NULL THEN 'PENTA6M' END pen6
                    into ESSALUD.dbo.ult_aten
                    FROM packages_packchildfollow""" % (request.GET['anio'], mes))

        a.execute("""SELECT cod_dep, cod_prov, cod_dist, cod_eess, establecimiento, ape_nombres, documento, fec_nac, Edad,
                CASE WHEN ULT_CRED IS NULL THEN
                        CASE WHEN Edad=0 THEN 'CTRLS RN'
                            WHEN Edad=1 THEN CONCAT(DATEADD(day, 30, fec_nac), ' / CRED1')
                            WHEN Edad=2 THEN CONCAT(DATEADD(day, 60, fec_nac), ' / CRED2')
                            WHEN Edad=3 THEN CONCAT(DATEADD(day, 90, fec_nac), ' / CRED3')
                            WHEN Edad=4 THEN CONCAT(DATEADD(day, 120, fec_nac), ' / CRED4')
                            WHEN Edad=5 THEN CONCAT(DATEADD(day, 150, fec_nac), ' / CRED5')
                            WHEN Edad=6 THEN CONCAT(DATEADD(day, 180, fec_nac), ' / CRED6')
                            WHEN Edad=7 THEN CONCAT(DATEADD(day, 210, fec_nac), ' / CRED7')
                            WHEN Edad=8 THEN CONCAT(DATEADD(day, 240, fec_nac), ' / CRED8')
                            WHEN Edad=9 THEN CONCAT(DATEADD(day, 270, fec_nac), ' / CRED9')
                            WHEN Edad=10 THEN CONCAT(DATEADD(day, 300, fec_nac), ' / CRED10')

apps/dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>{% block title %}EsSalud G{% endblock title %}</title>
    <link rel="icon" href='/static/img/favicon.png' type="image/x-icon">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-progressbar-3.3.4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pnotify.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="{% static 'css/footable.core.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_footable.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block styles %}
    <style>
        .ui-pnotify-title { font-size: 15px !important; }
    </style>
    {% endblock styles %}
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="{% url 'dashboard:dash' %}" class="site_title"><i class="fa fa-google"></i> <span>EsSalud</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        {% if request.user.id_person.sex == 'M' %}
                            <img src="{% static 'img/doctor.png' %}" alt="user" class="img-circle profile_img">
                        {% else %}
                            <img src="{% static 'img/nurse.png' %}" alt="user" class="img-circle profile_img">
                        {% endif %}
                    </div>
                    <div class="profile_info"> <span>Bienvenid@,</span><h2>{{ request.user.id_person.names }}</h2></div>
                </div>
                <!-- /menu profile quick info -->
                <br />
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                    <h3>{{ request.user.type_ca }} - {{ request.session.sytem.nombreca }}</h3>
                    <ul class="nav side-menu">
                        <li><a><i class="fa fa-bar-chart-o"></i> Tableros <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{% url 'boards:index_cov' %}">Tablero Cobertura</a></li>
                            </ul>
                        </li>
                        <li><a><i class="fa fa-desktop"></i> Paquete <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{% url 'packages:boys' %}">Niños</a></li>
                                <li><a href="{% url 'packages:pregnant' %}">Gestantes</a></li>
                            </ul>
                        </li>
                        <li><a><i class="fa fa-male"></i> Seguimiento <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{% url 'follow_up:index_boy' %}">Pacientes</a></li>
                                <li><a href="{% url 'follow_up:index_anemia' %}">Anemia Niños</a></li>
                                <li><a href="{% url 'follow_up:index_inmunization' %}">Inmunizaciones</a></li>
                            </ul>
                        </li>
                    </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->
                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'dashboard:logout' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class="navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    {% if request.user.id_person.sex == 'M' %}
                                        <img src="{% static 'img/doctor.png' %}" width="23" alt="user" class="img-circle border border-secondary mr-2">
                                    {% else %}
                                        <img src="{% static 'img/nurse.png' %}" width="23" alt="user" class="img-circle border border-secondary mr-2">
                                    {% endif %}
                                    {{ request.user.id_person.names }}
                                </a>
                                <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" data-toggle="modal" data-target=".change_pw"> Cambiar Contraseña</a>
                                    <a class="dropdown-item" href="{% url 'dashboard:logout' %}"><i class="fa fa-sign-out pull-right"></i> Cerrar Sesión</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <div class="right_col" role="main">
                {% block content %}
                {% endblock content %}
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <footer>
                <div class="pull-right"> EsSalud V.2.0 </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <div class="modal fade change_pw" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm">
          <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel2">Cambiar Contraseña</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <div id="appForPassword">
                    <form class="form-horizontal form-material" @submit.prevent="sendPass">
                        {% csrf_token %}
                        <!-- <input type="hidden" name="pid" id="pid" :value='[[person.pk]]' required> -->
                        <input type="hidden" id="pid" name="pid" value="{{request.user.id}}" required>
                        <div class="col-md-12 mb-2">
                            <label for="">Nueva contraseña</label>
                            <input type="password" id='password' name='password' class="form-control form-control-line">
                        </div>
                        <div class="col-md-12">
                            <label for="">Repita nueva contraseña</label>
                            <input type="password" id='password_r' name='password_r' class="form-control form-control-line">
                        </div>
                        <div class="col-md-12 mt-3">
                            <button type='submit' class="btn btn-sm btn-success"><span class="fa fa-save"></span> Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
          </div>
        </div>
    </div>

    <script src="{% static 'js/vue.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/select2.full.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/date.js' %}"></script>
    <script src="{% static 'js/bootstrap-progressbar.min.js' %}"></script>
    <script src="{% static 'js/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static 'js/pnotify.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/gauge.min.js' %}"></script>
    <script src="{% static 'js/footable.all.min.js' %}"></script>
    <script src="{% static 'js/footable-init.js' %}"></script>
    <script src="{% static 'js/hammer.min.js' %}"></script>
    <script src="{% static 'js/vue/profile.js' %}"></script>
    <script>
        Vue.directive('select2', {
            inserted: function (elem, fieldName) {
                $(elem).select2();
            },
            componentUpdated:function(el, binding) {
                Vue.nextTick(function () {
                    let options = binding.value || {};
                    // set up select2
                    $(el).select2(Object.assign({}, {
                    // Default options
                    }, options))
                    .on("select2:select select2:unselect", (e) => {
                        el.dispatchEvent(new Event('change', { target: e.target }));
                    });
                });
            },
        });
    </script>

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>

apps/dashboard/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>{% block title %}ESSALUD{% endblock title %}</title>
    <link rel="icon" href='/static/img/favicon.png' type="image/x-icon">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">

    {% block styles %}
    {% endblock styles %}

</head>
<body class="login">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 p-0 d-flex justify-content-center align-items-center">
                    <img src="{% static 'img/fondo1.png' %}" alt="fondo" class="img-fluid">
                </div>
                <div class="col-md-6 contents d-flex justify-content-center">
                    <div class="contForm">
                        <div class="mb-4 text-center">
                            <img src="{% static 'img/logoEssalud.png' %}" alt="Home"/>
                            <h1 class="text-dark">Bienvenidos</h1>
                        </div>
                        <form class="form-horizontal form-material" method="POST">
                            {% csrf_token %}
                            <div class="form-group first mb-3">
                                {{ form.username }}
                            </div>
                            <div class='col-md-12'>
                                {{ form.username.errors }}
                            </div>
                            <div class="form-group last mb-4">
                                {{ form.password }}
                            </div>
                            <div class='col-md-12'>
                                {{ form.password.errors }}
                            </div>
                            <input type="submit" value="ACCEDER" class="btn btn-block btn-primary">
                            <span class="d-block text-center my-3 text-muted">&mdash; Visite nuestras redes sociales &mdash;</span>
                            <div class="social-login text-center">
                                <a href="#" class="facebook">
                                    <span class="fa fa-facebook mr-3"></span>
                                </a>
                                <a href="#" class="twitter">
                                    <span class="fa fa-twitter mr-3"></span>
                                </a>
                                <a href="#" class="google">
                                    <span class="fa fa-google mr-3"></span>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>